version: '3.7'
services:
  db:
    build: ./neo4j
    image: hmiyakoshi0803/neo4j:4.0.2
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - ./neo4j/data:/data
      - ./neo4j/logs/:/logs
      - ./neo4j/conf/:/conf
    ulimits: 
      nofile:
        soft: "40000"
        hard: "40000"
